apiVersion: v1
kind: ServiceAccount
metadata:
  name: rds-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: flaskapp
  labels:
    app: flaskapp
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-cache-enable: "true"
    vault.hashicorp.com/role: "flaskapp"
    vault.hashicorp.com/agent-inject-secret-credentials.txt: "database/creds/dbrole"
    vault.hashicorp.com/agent-inject-template-credentials.txt: |
      {{- with secret "database/creds/dbrole" -}}
      {{ .Data | toUnescapedJSON }}
      {{- end -}}
spec:
  serviceAccountName: rds-sa
  containers:
    - name: flaskapp
      image: abdelalidocker/vault-flask-app
      env:
      - name: DB_HOST
        value: "database.civprmsgnbew.us-west-2.rds.amazonaws.com"
      - name: DB_DATABASE
        value: "demo"
